source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'haml'
gem 'net'
gem 'nokogiri'
gem 'httparty'
gem 'rest-client'
gem 'jquery-rails', '~> 4.0.4'